allprojects {
	repositories {
		google()
			jcenter()
	}
}

rootProject.buildDir = '../build'
subprojects {
	afterEvaluate { project ->
		if (project.hasProperty('android')) {
			project.android {
				if (namespace == null) {
					namespace project.group
				}
				// Avoid adding android.defaults.buildfeatures.buildconfig=true
				// to your gradle.properties file because that property is deprecated in AGP 8.0 and is scheduled to be removed in AGP 9.0.
				buildFeatures {
					if (buildConfig == null) {
						buildConfig true
					}
				}
			}
		}
	}
	project.buildDir = "${rootProject.buildDir}/${project.name}"
		project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
	delete rootProject.buildDir
}