// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdFLNjRj6EtKgvuyeyZZb6lwmSneDCltw',
    appId: '1:647188572266:android:32f5b010a7468bbf5c0213',
    messagingSenderId: '647188572266',
    projectId: 'zenith-monitor-a0d89',
    databaseURL: 'https://zenith-monitor-a0d89.firebaseio.com',
    storageBucket: 'zenith-monitor-a0d89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb0CYZjgUE0WzIxc_vfR26VWh08FpRW3g',
    appId: '1:647188572266:ios:3b7c8e4eb2980b995c0213',
    messagingSenderId: '647188572266',
    projectId: 'zenith-monitor-a0d89',
    databaseURL: 'https://zenith-monitor-a0d89.firebaseio.com',
    storageBucket: 'zenith-monitor-a0d89.appspot.com',
    androidClientId: '647188572266-j3201qobbgvq19oqso8978l6t62tl13q.apps.googleusercontent.com',
    iosClientId: '647188572266-c0r04kh4gg2f4jq60mg1dari157af9s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenithMonitor',
  );
}
